service: polgo-api-middleware-omie

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  timeout: 30

  environment:
    NODE_ENV: ${self:provider.stage}
    LOG_LEVEL: ${env:LOG_LEVEL, 'info'}
    POLGO_API_URL: ${env:POLGO_API_URL, 'https://integracaoomie.hapi.polgo.online/polgo'}
    OMIE_API_URL: ${env:OMIE_API_URL, 'https://appdevi-api.trafficmanager.net'}
    
    # DataExchange specific variables
    CASHOUT_API_URL: ${env:CASHOUT_API_URL, 'https://testewscashout.qrsorteios.com.br/6ef8c1ab-9064-4e38-82ee-5c9218ed8c13'}
    MAX_RETRIES: ${env:MAX_RETRIES, '3'}
    RETRY_DELAY: ${env:RETRY_DELAY, '1000'}
    REQUEST_TIMEOUT: ${env:REQUEST_TIMEOUT, '10000'}
    CACHE_TTL: ${env:CACHE_TTL, '3600'}

functions:
  omieWebhookHandler:
    handler: handler.omieWebhookHandler
    events:
      - http:
          path: polgo/integracao/webhook/omie
          method: post
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000 