service: polgo-api-middleware-omie

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    NODE_ENV: ${self:provider.stage}
    LOG_LEVEL: ${env:LOG_LEVEL, 'info'}
    POLGO_API_URL: ${env:POLGO_API_URL, 'https://integracaoomie.hapi.polgo.online/polgo'}
    POLGO_AUTH_URL: ${env:POLGO_AUTH_URL, 'https://auth-dev.polgo.com.br'}
    POLGO_WEBHOOK_URL: ${env:POLGO_WEBHOOK_URL, 'https://webhook-dev.polgo.com.br'}
    OMIE_API_KEY: ${env:OMIE_API_KEY, ''}
    OMIE_API_SECRET: ${env:OMIE_API_SECRET, ''}
    OMIE_APP_KEY: ${env:OMIE_APP_KEY, ''}
    OMIE_USUARIO: ${env:OMIE_USUARIO, 'omie'}
    OMIE_SENHA: ${env:OMIE_SENHA, 'omiepolgo'}
    OMIE_EMPRESA_ID: ${env:OMIE_EMPRESA_ID, 'cca39332-72c7-4f8c-b5f4-82d4944089e2'}
    CASHBACK_VALOR: ${env:CASHBACK_VALOR, '49.99'}
    NOTIFICATION_USUARIO: ${env:NOTIFICATION_USUARIO, '19995811172'}
    FLOW_CAIXA_ID: ${env:FLOW_CAIXA_ID, 'cx01'}
    # DataExchange specific variables
    CASHOUT_API_URL: ${env:CASHOUT_API_URL, 'https://testewscashout.qrsorteios.com.br/6ef8c1ab-9064-4e38-82ee-5c9218ed8c13'}
    CASHOUT_CALCULATION_URL: ${env:CASHOUT_CALCULATION_URL, 'https://testews.polgo.com.br'}
    CASHOUT_VALOR: ${env:CASHOUT_VALOR, '0.15'}
    CASHOUT_VALOR_TOTAL_COMPRA: ${env:CASHOUT_VALOR_TOTAL_COMPRA, '15'}
    DISCOUNT_API_URL: ${env:DISCOUNT_API_URL, 'https://appdevi-api.trafficmanager.net'}
    DISCOUNT_APP_KEY: ${env:DISCOUNT_APP_KEY, '5d90522b-eceb-4353-a176-fbcef8a728d5'}
    DISCOUNT_APP_SECRET: ${env:DISCOUNT_APP_SECRET, 'LF5GMDtCVm021kH7BBsP7Uzx5ZO0X2kktkF7rvEPeWc+miiYJZJE6Y8EuwcPjECesBzlhdsWteBsZpAqX6ufGjDt/+nu9Ev75Cx8qEbnF640xlGkRDGUel8UfUUd/FHx91vKIGCFfaDQ4Jg5g7YcGcYKnofcC/YHfdLskTqiXxo='}
    DISCOUNT_EMPRESA_ID: ${env:DISCOUNT_EMPRESA_ID, 'b1e17e5a-fa73-4f29-9289-46e7c2a3aa5d'}
    DISCOUNT_CAIXA_ID: ${env:DISCOUNT_CAIXA_ID, '0c200257-2d47-442c-9b98-38e753bae90f'}
    DISCOUNT_VALOR: ${env:DISCOUNT_VALOR, '10.00'}
    MAX_RETRIES: ${env:MAX_RETRIES, '3'}
    RETRY_DELAY: ${env:RETRY_DELAY, '1000'}
    REQUEST_TIMEOUT: ${env:REQUEST_TIMEOUT, '5000'}
    LAMBDA_TIMEOUT: ${env:LAMBDA_TIMEOUT, '30'}
    CACHE_TTL: ${env:CACHE_TTL, '3600'}

functions:
  omieWebhookHandler:
    handler: handler.omieWebhookHandler
    events:
      - http:
          path: polgo/integracao/webhook/omie
          method: post
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000 